### ISSUE TITLE
BUG :D

### ISSUE THREAD

**Issue by AirLeMineral** [MMO-X/Resource-Pack#10]
Scorehud & health bart bug like this
And if change gamemode survival can fly. Thanks :D
![IMG_20210531_210735](https://user-images.githubusercontent.com/68475999/120205710-7885ad00-c254-11eb-82be-9f18f4dbe88b.jpg)

**Comment by xxAROX** [comment]
Only support for mmo.xxarox.de servers.

**Comment by xxAROX** [comment]
Health and armor will not displayed, because you have 100 default health

**Comment by AirLeMineral** [comment]
> Only support for mmo.xxarox.de servers.

Lmao
